export const BASE_URL = import.meta.env.VITE_API_GATEWAY_URL;

export const MASTER_APIS = {
	SPLASH: `${BASE_URL}/core/splash-info`,
	LOGIN: `${BASE_URL}/user-login`,
};

export const APP_NAVLINKS = {
	BAKERY: "/pos/bakery",
	SALES: "/inventory/sales",
	HOLD_SALES: "/inventory/sales/hold",
	SALES_NEW: "/inventory/sales/new",
	SALES_EDIT: "/inventory/sales/edit",
	PURCHASE: "/inventory/purchase",
	PURCHASE_NEW: "/inventory/purchase/new",
	PURCHASE_EDIT: "/inventory/purchase/edit",
	REQUISITION: "/inventory/requisition",
	REQUISITION_NEW: "/inventory/requisition/new",
	REQUISITION_EDIT: "/inventory/requisition/edit",
	PURCHASE_RETURN: "/inventory/purchase-return",
	PURCHASE_RETURN_NEW: "/inventory/purchase-return/new",
	PURCHASE_RETURN_EDIT: "/inventory/purchase-return/edit",
	SALES_RETURN: "/inventory/sales-return",
	SALES_RETURN_NEW: "/inventory/sales-return/new",
	SALES_RETURN_EDIT: "/inventory/sales-return/edit",
	OPENING_STOCK: "/inventory/opening-stock",
	STOCK: "/inventory/stock",
	ACTIVATE: "/activate",
	LOGIN: "/login",
	DASHBOARD: "/dashboard",
	CUSTOMERS: "/core/customers",
	SETTINGS: "/inventory/config",
};

export const APP_APIS = {
	CONFIG: "/inventory/config",
	LOGIN: "/auth/login",
	REGISTER: "/auth/register",
	LOCAL_STORAGE_VENDORS: "/core/vendor/local-storage",
	VENDORS: "/core/vendor",
	LOGOUT: "/auth/logout",
	RESET_PASSWORD: "/auth/reset-password",
	SYNC_POS: "/inventory/pos/data-process",
	CATEGORIES: "/inventory/select/category",
	INVOICE_MODE: "/inventory/pos/check/invoice-mode",
	INVOICE_DETAILS: "/inventory/pos/invoice-details",
	INLINE_UPDATE: "/inventory/pos/inline-update",
	SALES_COMPLETE: "/inventory/pos/sales-complete",
	SALES: "/inventory/sales",
	REQUISITION: "/inventory/requisition",
	PURCHASE_RETURN: "/inventory/purchase/return",
	SALES_RETURN: "/inventory/sales/return",
	CUSTOMERS: "/core/customer",
	SETTINGS: "/core/select/setting",
	INVENTORY_SETTINGS: "/inventory/select/setting",
	INVENTORY_PRODUCT: "/inventory/product",
	INVENTORY_CATEGORIES: "/inventory/select/category",
	INVENTORY_PARTICULAR: "/inventory/select/particular",
	PURCHASE: "/inventory/purchase",
	CHANGE_PASSWORD: "/core/change-password",
	PURCHASE_CONFIG: "/domain/config/inventory-purchase",
	DAILY_SUMMARY: "/inventory/report/daily-summary",
};
